### ISSUE TITLE
Dashboard shows 500 error & 404 error

### ISSUE THREAD

**Issue by numitec** [tbreuss/yii2-inertia#5]
Hello there,

  just trying and learning inertia.js & vue, I test this demo and, well, the other options work but the initial page throws:

`500 error 404 error
`

  Thanks!

**Comment by tbreuss** [comment]
@numitec Thanks for reporting.

Are you talking about this? See screenshot from original demo application at https://demo.inertiajs.com

<img width="1189" alt="demo inertiajs" src="https://user-images.githubusercontent.com/1334161/109333353-a4f9e980-785f-11eb-8626-96e3df1dced6.png">

If yes, then this is an intended behavior (from the original demo) and was just copied for the yii2-inertia demo.

**Comment by numitec** [comment]
Yes. Thank you.

BTW, I like inertia.js and I'll try it with Svelte; perhaps I'll ask a few more questions.

Thanks again.

**Comment by tbreuss** [comment]
Thanks. But, I'm not the author of inertia.js.

Be sure to address your questions to the right repo. This repo is a yii2 community adapter for inertia. The right repo is maybe https://github.com/inertiajs
